name: innerpod
description: "A session timer with session logged to your Solid Pod."
publish_to: "none"
version: 1.7.4+71

environment:
  sdk: ">=3.2.5 <4.0.0"

# To automatically upgrade package dependencies:
#
#   flutter pub upgrade --major-versions
#
# To see which dependencies have newer versions available:
#
#   flutter pub outdated
#
# (gjw 20250722)

dependencies:
  audioplayers: ^6.1.0
  cupertino_icons: ^1.0.2
  circular_countdown_timer: ^0.2.3
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.4
  gap: ^3.0.1
  intl: ^0.20.2
  markdown_tooltip: ^0.0.7
  package_info_plus: ^8.3.0
  solidpod: ^0.7.4
  url_launcher: ^6.3.0
  version_widget: ^1.0.4
  wakelock_plus: ^1.1.4

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  ubuntu_lints: ^0.4.1+1

flutter:
  assets:
    - assets/images/inner_icon.png
    - assets/images/inner_image.jpg
    - assets/sounds/dong.mp3
    - assets/sounds/intro.mp3
    - assets/sounds/session_guide.mp3
    - assets/sounds/session_intro.mp3
    - assets/sounds/session_outro.mp3
  uses-material-design: true

# Define launcher icons for all platforms (except Linux) so icons for
# the apps can be automatically updated using:
#
# `dart run flutter_launcher_icons`
#
# (gjw 20250429)

flutter_launcher_icons:
  image_path: "assets/icon/icon.png"
  android: "launcher_icon"
  min_sdk_android: 21 # android min sdk min:16, default 21  ios: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    # background_color: "#hexcode"
    # theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"
