name: innerpod
description: "A session timer with session logged to your Solid Pod."
publish_to: 'none'
version: 1.6.4+63

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.1
  cupertino_icons: ^1.0.2
  circular_countdown_timer: ^0.2.3
  flutter_markdown: ^0.6.18
  intl:
  package_info_plus: 
  solidpod:
  wakelock_plus: ^1.1.4

dependency_overrides:
  intl: ^0.19.0  # Eventually remove. Through solidpod, solid-auth depends on intl-0.19.0
  
dev_dependencies:
  # The original `dart-code-metrics` is end of live and has migrated to
  # a paid service. This fork maintains it's compatibility with the
  # latest flutter.

  # dart_code_metrics:
  #   git:
  #     url: https://github.com/Zheyuan-Robert-Xu/dart-code-metrics.git
  #     ref: master

  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  # solid_lints: ^0.1.1
  ubuntu_lints: ^0.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/inner_icon.png
    - assets/images/inner_image.jpg
    - assets/sounds/dong.ogg
    - assets/sounds/intro.ogg
    - assets/sounds/session_guide.ogg
    - assets/sounds/session_intro.ogg
    - assets/sounds/session_outro.ogg

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    #background_color: "#hexcode"
    #theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"
