/// A session timer with session logged to your Solid Pod.
//
// Time-stamp: <Tuesday 2026-02-10 15:44:48 +1100 Graham Williams>
//
/// Copyright (C) 2024-2025, Togaware Pty Ltd
///
/// Licensed under the GNU General Public License, Version 3 (the "License");
///
/// License: https://opensource.org/license/gpl-3-0
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
// details.
//
// You should have received a copy of the GNU General Public License along with
// this program.  If not, see <https://opensource.org/license/gpl-3-0>.
///
/// Authors: Graham Williams

library;

import 'package:flutter/material.dart';

import 'package:flutter_markdown_plus/flutter_markdown_plus.dart';
import 'package:gap/gap.dart';
import 'package:package_info_plus/package_info_plus.dart';
import 'package:solidpod/solidpod.dart';
import 'package:url_launcher/url_launcher.dart';

import 'package:innerpod/constants/colours.dart';
import 'package:innerpod/utils/word_wrap.dart';
import 'package:innerpod/widgets/history.dart';
import 'package:innerpod/widgets/instructions.dart';
import 'package:innerpod/widgets/timer.dart';

/// A widget for the actuall app's main home page.

class Home extends StatefulWidget {
  /// Constructor for the home screen.

  const Home({super.key});

  @override
  HomeState createState() => HomeState();
}

///

class HomeState extends State<Home> with SingleTickerProviderStateMixin {
  // We will populate the app version shortly.

  var _appVersion = '';

  final String _changelogUrl =
      'https://github.com/gjwgit/innerpod/blob/dev/CHANGELOG.md';

  final _about = wordWrap('''

  Inner Pod is an app for timing meditation sessions and, optionally, storing a
  log of your meditation sessions to your Pod. A session, in fact, can be
  anything.  The app is commonly used for contemplative or silent meditation as
  is the tradition in many cultures and religions.  The concept for the app and
  images were generated by large language models.

  The app is written in Flutter and the open source code is available from
  **github**.  You can also run the app **online** through your browser.

  **GitHub** [https://github.com/gjwgit/innerpod](https://github.com/gjwgit/innerpod)

  **OnLine** [https://innerpod.solidcommunity.au](https://innerpod.solidcommunity.au)

  **Author** [Graham&nbsp;Williams](https://togaware.com/graham.williams.html)
      ''');

  // Helper function to load the app name and version.

  Future<void> _loadAppInfo() async {
    final packageInfo = await PackageInfo.fromPlatform();
    if (mounted) {
      setState(() {
        _appVersion = packageInfo.version; // Set app version from package info
      });
    }
  }

  @override
  void initState() {
    super.initState();

    // Get the app name and version.

    _loadAppInfo();
  }

  // Track which item is selected in the nav bar.

  int _selectedIndex = 0;

  void _onItemTapped(int index) {
    setState(() {
      _selectedIndex = index;
    });
  }

  final List<Widget> _pages = <Widget>[
    const Timer(),
    const Instructions(),
    const History(),
  ];

  @override
  Widget build(BuildContext context) {
    // final dateStr = DateFormat('dd MMMM yyyy').format(DateTime.now());

    return Scaffold(
      backgroundColor: background,
      appBar: AppBar(
        title: Row(
          children: [
            Image.asset('assets/images/inner_icon.png', width: 40, height: 40),
            const SizedBox(width: 20),
            const Text('Inner Pod'),
          ],
        ),
        backgroundColor: border,
        actions: [
          GestureDetector(
            onTap: () async {
              final url = Uri.parse(_changelogUrl);
              if (await canLaunchUrl(url)) {
                await launchUrl(url);
              } else {
                debugPrint('Could not launch $_changelogUrl');
              }
            },
            child: MouseRegion(
              cursor: SystemMouseCursors.click,
              child: Text(
                'Version $_appVersion',
                style: const TextStyle(color: Colors.deepPurple, fontSize: 10),
              ),
            ),
          ),
          // TODO 20250730 gjw MIGRATE TO VersionWidget
          //
          // I was not able to get this working - the value of _appVersion
          // remains empty in the VersionWidget() even though it is correct in the
          // Text().
          //
          // Text('XX $_appVersion'),
          // VersionWidget(
          //   version: 'YY $_appVersion',
          //   changelogUrl: _changelogUrl,
          //   showDate: false,
          //   userTextStyle: const TextStyle(
          //     color: Colors.deepPurple,
          //     fontSize: 10,
          //   ),
          // ),
          // Text('Version $_appVersion', style: const TextStyle(fontSize: 10)),
          const SizedBox(width: 50),
          IconButton(
            icon: const Icon(Icons.info),
            onPressed: () async {
              final appInfo = await getAppNameVersion();
              final appName = appInfo.name;

              // Note the use of the conditional with `context.mounted` to avoid
              // the "Don't use 'BuildContext's across async gaps" warning.

              if (context.mounted) {
                showAboutDialog(
                  context: context,
                  applicationIcon: Image.asset(
                    'assets/images/inner_icon.png',
                    width: 100,
                    height: 100,
                  ),
                  applicationName:
                      '${appName[0].toUpperCase()}${appName.substring(1)}',
                  applicationVersion: appInfo.version,
                  applicationLegalese: '© 2024 Togaware',
                  children: [
                    const Gap(20),
                    MarkdownBody(
                      data: _about,
                      selectable: true,
                      softLineBreak: true,
                      onTapLink: (text, href, about) {
                        final url = Uri.parse(href ?? '');
                        launchUrl(url);
                      },
                    ),
                  ],
                );
              }
            },
            tooltip: 'Popup a window about the app.',
          ),
        ],
      ),
      body: Center(child: _pages.elementAt(_selectedIndex)), //Timer()),
      bottomNavigationBar: BottomNavigationBar(
        backgroundColor: border,
        items: const <BottomNavigationBarItem>[
          BottomNavigationBarItem(
            icon: Icon(Icons.home), //, color: Colors.black),
            label: 'Home',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.text_snippet),
            label: 'Text',
          ),
          BottomNavigationBarItem(icon: Icon(Icons.settings), label: 'History'),
        ],
        currentIndex: _selectedIndex,
        selectedItemColor: Colors.amber[800],
        onTap: _onItemTapped,
      ),
    );
  }
}
