// About dialog for the app.
//
// Time-stamp: <2026-02-12 20:40:00 Graham Williams>
//
// Copyright (C) 2024-2026, Togaware Pty Ltd
//
// Licensed under the GNU General Public License, Version 3 (the "License");
//
// License: https://opensource.org/license/gpl-3-0
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
// details.
//
// You should have received a copy of the GNU General Public License along with
// this program.  If not, see <https://opensource.org/license/gpl-3-0>.
///
/// Authors: Graham Williams
library;

import 'package:flutter/material.dart';

import 'package:flutter_markdown_plus/flutter_markdown_plus.dart';
import 'package:gap/gap.dart';
import 'package:solidpod/solidpod.dart';
import 'package:url_launcher/url_launcher.dart';

import 'package:innerpod/utils/word_wrap.dart';

/// Display the about dialog for the app.

Future<void> showAppAboutDialog(BuildContext context) async {
  final appInfo = await getAppNameVersion();
  final appName = appInfo.name;

  final about = wordWrap('''

  Inner Pod is an app for timing meditation sessions and, optionally, storing a
  log of your meditation sessions to your Pod. A session, in fact, can be
  anything.  The app is commonly used for contemplative or silent meditation as
  is the tradition in many cultures and religions. The blue progress circle
  provides a visual cue that the session is active and audio may be
  playing. The concept for the app and images were generated by large
  language models.

  The app is written in Flutter and the open source code is available from
  **github**.  You can also run the app **online** through your browser.

  **GitHub** [https://github.com/gjwgit/innerpod](https://github.com/gjwgit/innerpod)

  **OnLine** [https://innerpod.solidcommunity.au](https://innerpod.solidcommunity.au)

  **Author** [Graham&nbsp;Williams](https://togaware.com/graham.williams.html)
      ''');

  if (context.mounted) {
    showAboutDialog(
      context: context,
      applicationIcon: Image.asset(
        'assets/images/inner_icon.png',
        width: 100,
        height: 100,
      ),
      applicationName: '${appName[0].toUpperCase()}${appName.substring(1)}',
      applicationVersion: appInfo.version,
      applicationLegalese: '© 2024 Togaware',
      children: [
        const Gap(20),
        MarkdownBody(
          data: about,
          selectable: true,
          softLineBreak: true,
          onTapLink: (text, href, about) {
            final url = Uri.parse(href ?? '');
            launchUrl(url);
          },
        ),
      ],
    );
  }
}
