name: Build Installers

on:
  push:
    branches:
      - dev

jobs:

  build-linux-zip:
    if: contains(github.event.head_commit.message, 'bump version')
    runs-on: ubuntu-20.04

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Confirm Branch
        run: git status

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64
          flutter-version: 3.24.3

      - name: Confirm Flutter Version
        run: flutter --version

      - name: Install OS Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
          sudo apt-get install -y clang cmake
          sudo apt-get install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev

      - name: Install flutter project dependencies
        run: flutter pub get
        
      - name: Enable Linux Build
        run: flutter config --enable-linux-desktop

      - name: Build Artifact
        run: flutter build linux --release

      - name: Set version
        run: |
          echo "APP_VERSION=$(grep version pubspec.yaml |cut -d ':' -f 2 | sed 's/ //g')" >> $GITHUB_ENV
          echo $APP_VERSION

      - name: Zip Bundle
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: innerpod-${{ env.APP_VERSION }}-linux.zip
          directory: build/linux/x64/release/bundle

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: innerpod-linux-zip
          path: build/linux/x64/release/bundle/innerpod-${{ env.APP_VERSION }}-linux.zip

########################################################################

  build-windows-inno:
    if: contains(github.event.head_commit.message, 'bump version')
    runs-on: windows-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          flutter-version: '3.24.3'

      - name: Install Project Dependencies
        run: flutter pub get

      - name: Enable Windows Build
        run: flutter config --enable-windows-desktop

      - name: Build Artifact
        run: flutter build windows

      - name: Get Version from pubspec.yaml
        run: |
          $version = (Get-Content pubspec.yaml | Select-String '^version:[^^]*' | ForEach-Object { $_.ToString().Split(":")[1].Trim().Split("+")[0].Trim() })
          echo "APP_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Compile .ISS to .EXE Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: installers/innerpod-windows.iss
          options: /O+

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: innerpod-windows-inno
          path: D:\a\innerpod\innerpod\installers\installers\innerpod-0.0.0.exe

########################################################################

  build-windows-zip:
    if: contains(github.event.head_commit.message, 'bump version')
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          flutter-version: '3.24.3'
      - name: Install project dependencies
        run: flutter pub get
      - name: Enable windows build
        run: flutter config --enable-windows-desktop
      - name: Build artifacts
        run: flutter build windows --release
      - name: Set version
        run: |
          echo "APP_VERSION=$(grep version pubspec.yaml |cut -d ':' -f 2 | sed 's/ //g')" >> $GITHUB_ENV
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: innerpod-${{ env.APP_VERSION }}-windows.zip
          directory: build/windows/x64/runner/Release
      - name: Windows Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: build/windows/x64/runner/Release/innerpod-${{ env.APP_VERSION }}-windows.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: innerpod-windows-zip
          path: build/windows/x64/runner/Release/innerpod-${{github.ref_name}}-windows.zip

########################################################################

  build-macos-zip:
    if: contains(github.event.head_commit.message, 'bump version')
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          flutter-version: '3.24.3'
      - name: Install project dependencies
        run: flutter pub get
      - name: Enable macOS build
        run: flutter config --enable-macos-desktop
      - name: Build artifacts
        run: flutter build macos --release
      - name: Set version
        run: |
          echo "APP_VERSION=$(grep version pubspec.yaml |cut -d ':' -f 2 | sed 's/ //g')" >> $GITHUB_ENV
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: build/macos/Build/Products/Release
          filename: innerpod-${{ env.APP_VERSION }}-macos.zip
      - run: ls -lh build/macos/Build/Products/Release
      - name: macOS Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: build/macos/Build/Products/Release/innerpod-${{ env.APP_VERSION }}-macos.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: innerpod-macos-zip
          path: build/macos/Build/Products/Release/innerpod-${{ env.APP_VERSION }}-macos.zip
